title: "Nguyen Quang Huy"
url: https://huynq03.github.io
repository: "huynq03/huynq03.github.io"
author:
  email: "huyquangnguyenwork@gmail.com"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: portfolio-home

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
